HINGLISH_TO_DEVANAGARI = {

    # ══════════════════════════════════════════════════════
    #  PRONOUNS
    # ══════════════════════════════════════════════════════
    "main": "मैं",
    "mein": "मैं",
    "mai": "मैं",# sak
    "hum": "हम",
    "hume": "हमें",
    "humko": "हमको",
    "humara": "हमारा",
    "humari": "हमारी",
    "humare": "हमारे",
    "mujhe": "मुझे",
    "mujhko": "मुझको",
    "mera": "मेरा",
    "meri": "मेरी",
    "mere": "मेरे",
    "tum": "तुम",
    "tumhe": "तुम्हें",
    "tumhara": "तुम्हारा",
    "tumhari": "तुम्हारी",
    "tumhare": "तुम्हारे",
    "tumko": "तुमको",
    "tu": "तू",
    "tujhe": "तुझे",
    "tera": "तेरा",
    "teri": "तेरी",
    "tere": "तेरे",
    "aap": "आप",
    "aapko": "आपको",
    "aapka": "आपका",
    "aapki": "आपकी",
    "aapke": "आपके",
    "woh": "वो",
    "wo": "वो",
    "use": "उसे",
    "usse": "उससे",
    "uska": "उसका",
    "uski": "उसकी",
    "uske": "उसके",
    "unhe": "उन्हें",
    "unka": "उनका",
    "unki": "उनकी",
    "unke": "उनके",
    "yeh": "यह",
    "ye": "यह",
    "isse": "इससे",
    "isko": "इसको",
    "isne": "इसने",
    "iska": "इसका",
    "iski": "इसकी",
    "iske": "इसके",
    "yeh": "यह",
    "inhone": "इन्होंने",
    "inhe": "इन्हें",
    "inका": "इनका",
    "inka": "इनका",
    "inki": "इनकी",
    "inke": "इनके",
    "khud": "खुद",
    "apne": "अपने",
    "apna": "अपना",
    "apni": "अपनी",
    "apko": "अपको",

    # ══════════════════════════════════════════════════════
    #  COMMON VERBS — BASE / ROOT FORMS
    # ══════════════════════════════════════════════════════
    "hai": "है",
    "hain": "हैं",
    "ho": "हो",
    "tha": "था",
    "thi": "थी",
    "the": "थे",
    "hoga": "होगा",
    "hogi": "होगी",
    "honge": "होंगे",
    "hua": "हुआ",
    "hui": "हुई",
    "hue": "हुए",
    "hona": "होना",
    "hoti": "होती",
    "hota": "होता",
    "hote": "होते",
    "karo": "करो",
    "karna": "करना",
    "karta": "करता",
    "karti": "करती",
    "karte": "करते",
    "kiya": "किया",
    "ki": "की",
    "karein": "करें",
    "kare": "करे",
    "karega": "करेगा",
    "karegi": "करेगी",
    "karenge": "करेंगे",
    "karo": "करो",
    "karke": "करके",
    "karna": "करना",
    "kar": "कर",
    "dena": "देना",
    "deta": "देता",
    "deti": "देती",
    "dete": "देते",
    "dene":"देने",
    "diya": "दिया",
    "di": "दी",
    "diye": "दिए",
    "de": "दे",
    "do": "दो",
    "dega": "देगा",
    "degi": "देगी",
    "denge": "देंगे",
    "lena": "लेना",
    "leta": "लेता",
    "leti": "लेती",
    "lete": "लेते",
    "liya": "लिया",
    "le": "ले",
    "lo": "लो",
    "lega": "लेगा",
    "legi": "लेगी",
    "lenge": "लेंगे",
    "jaana": "जाना",
    "jaata": "जाता",
    "jaati": "जाती",
    "jaate": "जाते",
    "gaya": "गया",
    "gayi": "गई",
    "gaye": "गए",
    "jao": "जाओ",
    "jaa": "जा",
    "jayega": "जाएगा",
    "jayegi": "जाएगी",
    "jayenge": "जाएंगे",
    "aana": "आना",
    "aata": "आता",
    "aati": "आती",
    "aate": "आते",
    "aaya": "आया",
    "aayi": "आई",
    "aaye": "आए",
    "aao": "आओ",
    "aa": "आ",
    "aayega": "आएगा",
    "aayegi": "आएगी",
    "aayenge": "आएंगे",
    "bolna": "बोलना",
    "bolta": "बोलता",
    "bolti": "बोलती",
    "bolte": "बोलते",
    "bola": "बोला",
    "boli": "बोली",
    "bole": "बोले",
    "bolo": "बोलो",
    "bol": "बोल",
    "bolega": "बोलेगा",
    "bolegi": "बोलेगी",
    "bolenge": "बोलेंगे",
    "batana": "बताना",
    "batata": "बताता",
    "batati": "बताती",
    "batate": "बताते",
    "bataya": "बताया",
    "batayi": "बताई",
    "bataye": "बताए",
    "batao": "बताओ",
    "bata": "बता",
    "batate": "बताते",
    "batayega": "बताएगा",
    "dekhna": "देखना",
    "dekhta": "देखता",
    "dekhti": "देखती",
    "dekhte": "देखते",
    "dekha": "देखा",
    "dekhi": "देखी",
    "dekhe": "देखे",
    "dekho": "देखो",
    "dekh": "देख",
    "dekhega": "देखेगा",
    "sunna": "सुनना",
    "sunta": "सुनता",
    "sunti": "सुनती",
    "sunte": "सुनते",
    "suna": "सुना",
    "suni": "सुनी",
    "sune": "सुने",
    "suno": "सुनो",
    "sun": "सुन",
    "samajhna": "समझना",
    "samajhta": "समझता",
    "samajhti": "समझती",
    "samajhte": "समझते",
    "samjha": "समझा",
    "samjhi": "समझी",
    "samjhe": "समझे",
    "samjho": "समझो",
    "samajh": "समझ",
    "padhna": "पढ़ना",
    "padhta": "पढ़ता",
    "padhti": "पढ़ती",
    "padhte": "पढ़ते",
    "padha": "पढ़ा",
    "padhi": "पढ़ी",
    "padhe": "पढ़े",
    "padho": "पढ़ो",
    "padh": "पढ़",
    "likhna": "लिखना",
    "likhta": "लिखता",
    "likhti": "लिखती",
    "likhte": "लिखते",
    "likha": "लिखा",
    "likhi": "लिखी",
    "likhe": "लिखे",
    "likho": "लिखो",
    "likh": "लिख",
    "nikalna": "निकालना",
    "nikalta": "निकालता",
    "nikalti": "निकालती",
    "nikalte": "निकालते",
    "nikala": "निकाला",
    "nikali": "निकाली",
    "nikale": "निकाले",
    "nikalo": "निकालो",
    "nikal": "निकाल",
    "chahna": "चाहना",
    "chahta": "चाहता",
    "chahti": "चाहती",
    "chahte": "चाहते",
    "chaho": "चाहो",
    "chahiye": "चाहिए",
    "chahie": "चाहिए",
    "sochna": "सोचना",
    "sochta": "सोचता",
    "sochti": "सोचती",
    "sochte": "सोचते",
    "socha": "सोचा",
    "socho": "सोचो",
    "soch": "सोच",
    "milna": "मिलना",
    "milta": "मिलता",
    "milti": "मिलती",
    "milte": "मिलते",
    "mila": "मिला",
    "mili": "मिली",
    "mile": "मिले",
    "milo": "मिलो",
    "mil": "मिल",
    "rakhna": "रखना",
    "rakhta": "रखता",
    "rakhti": "रखती",
    "rakhte": "रखते",
    "rakha": "रखा",
    "rakhi": "रखी",
    "rakhe": "रखे",
    "rakho": "रखो",
    "rakh": "रख",
    "banana": "बनाना",
    "banata": "बनाता",
    "banati": "बनाती",
    "banate": "बनाते",
    "banaya": "बनाया",
    "banayi": "बनाई",
    "banaye": "बनाए",
    "banao": "बनाओ",
    "bana": "बना",
    "khana": "खाना",
    "khata": "खाता",
    "khati": "खाती",
    "khate": "खाते",
    "khaya": "खाया",
    "khayi": "खाई",
    "khaye": "खाए",
    "khao": "खाओ",
    "kha": "खा",
    "peena": "पीना",
    "peeta": "पीता",
    "peeti": "पीती",
    "peete": "पीते",
    "piya": "पिया",
    "piyo": "पियो",
    "pi": "पी",
    "khulna": "खुलना",
    "khulta": "खुलता",
    "khula": "खुला",
    "kholna": "खोलना",
    "kholta": "खोलता",
    "khola": "खोला",
    "kholo": "खोलो",
    "khol": "खोल",
    "band": "बंद",
    "bandh": "बंद",
    "banana": "बनाना",
    "todna": "तोड़ना",
    "toda": "तोड़ा",
    "todo": "तोड़ो",
    "tod": "तोड़",
    "chalana": "चलाना",
    "chalata": "चलाता",
    "chalati": "चलाती",
    "chalate": "चलाते",
    "chalaya": "चलाया",
    "chalo": "चलो",
    "chal": "चल",
    "rukna": "रुकना",
    "rukta": "रुकता",
    "ruka": "रुका",
    "ruko": "रुको",
    "ruk": "रुक",
    "uthna": "उठना",
    "uthta": "उठता",
    "utha": "उठा",
    "utho": "उठो",
    "uth": "उठ",
    "baithna": "बैठना",
    "baithta": "बैठता",
    "baitha": "बैठा",
    "baitho": "बैठो",
    "baith": "बैठ",
    "jaanna": "जानना",
    "jaanta": "जानता",
    "jaanti": "जानती",
    "jaante": "जानते",
    "jaana": "जाना",
    "puchna": "पूछना",
    "puchta": "पूछता",
    "pucha": "पूछा",
    "pucho": "पूछो",
    "puch": "पूछ",
    "poochna": "पूछना",
    "poochta": "पूछता",
    "poocha": "पूछा",
    "poocho": "पूछो",
    "pooch": "पूछ",
    "bhejana": "भेजना",
    "bhejta": "भेजता",
    "bheja": "भेजा",
    "bhejo": "भेजो",
    "bhej": "भेज",
    "lana": "लाना",
    "lata": "लाता",
    "lati": "लाती",
    "late": "लाते",
    "laya": "लाया",
    "layi": "लाई",
    "laye": "लाए",
    "lao": "लाओ",
    "la": "ला",
    "dhoondna": "ढूंढना",
    "dhoondta": "ढूंढता",
    "dhoonda": "ढूंढा",
    "dhoondhna": "ढूंढना",
    "dhundna": "ढूंढना",
    "dhunda": "ढूंढा",
    "dhundo": "ढूंढो",
    "dhund": "ढूंढ",
    "maanna": "मानना",
    "maanta": "मानता",
    "maanti": "मानती",
    "maante": "मानते",
    "maana": "माना",
    "maano": "मानो",
    "maan": "मान",
    "rokna": "रोकना",
    "rokta": "रोकता",
    "roka": "रोका",
    "roko": "रोको",
    "rok": "रोक",
    "chhodna": "छोड़ना",
    "chhodta": "छोड़ता",
    "chhoda": "छोड़ा",
    "chhodo": "छोड़ो",
    "chhod": "छोड़",
    "chodna": "छोड़ना",
    "choda": "छोड़ा",
    "chodo": "छोड़ो",
    "chod": "छोड़",
    "sikhna": "सीखना",
    "sikhta": "सीखता",
    "sikha": "सीखा",
    "sikho": "सीखो",
    "sikh": "सीख",
    "batana": "बताना",
    "yaad": "याद",
    "yaad karna": "याद करना",
    "bhoolna": "भूलना",
    "bhoolta": "भूलता",
    "bhoola": "भूला",
    "bhoolo": "भूलो",
    "bhool": "भूल",
    "hasna": "हँसना",
    "hasta": "हँसता",
    "hasa": "हँसा",
    "haso": "हँसो",
    "has": "हँस",
    "rona": "रोना",
    "rota": "रोता",
    "roti": "रोती",
    "rote": "रोते",
    "roya": "रोया",
    "royi": "रोई",
    "roye": "रोए",
    "ro": "रो",
    "darna": "डरना",
    "darta": "डरता",
    "dara": "डरा",
    "daro": "डरो",
    "dar": "डर",
    "girna": "गिरना",
    "girta": "गिरता",
    "gira": "गिरा",
    "giro": "गिरो",
    "gir": "गिर",
    "bhagna": "भागना",
    "bhagta": "भागता",
    "bhaga": "भागा",
    "bhaago": "भागो",
    "bhaag": "भाग",
    "bachna": "बचना",
    "bachta": "बचता",
    "bacha": "बचा",
    "bacho": "बचो",
    "bach": "बच",
    "khona": "खोना",
    "khota": "खोता",
    "khoya": "खोया",
    "khoyi": "खोई",
    "khoye": "खोए",
    "kho": "खो",
    "paana": "पाना",
    "paata": "पाता",
    "paati": "पाती",
    "paate": "पाते",
    "paya": "पाया",
    "payi": "पाई",
    "paye": "पाए",
    "pao": "पाओ",
    "pa": "पा",
    "rehna": "रहना",
    "rehta": "रहता",
    "rehti": "रहती",
    "rehte": "रहते",
    "raha": "रहा",
    "rahi": "रही",
    "rahe": "रहे",
    "raho": "रहो",
    "reh": "रह",
    "sona": "सोना",
    "sota": "सोता",
    "soti": "सोती",
    "sote": "सोते",
    "soya": "सोया",
    "soyi": "सोई",
    "soye": "सोए",
    "so": "सो",
    "uthana": "उठाना",
    "uthata": "उठाता",
    "uthaya": "उठाया",
    "uthao": "उठाओ",
    "utha": "उठा",
    "ghumna": "घूमना",
    "ghumta": "घूमता",
    "ghuma": "घूमा",
    "ghumo": "घूमो",
    "ghum": "घूम",
    "khelna": "खेलना",
    "khelta": "खेलता",
    "khelti": "खेलती",
    "khelte": "खेलते",
    "khela": "खेला",
    "kheli": "खेली",
    "khele": "खेले",
    "khelo": "खेलो",
    "khel": "खेल",
    "gaana": "गाना",
    "gaata": "गाता",
    "gaati": "गाती",
    "gaate": "गाते",
    "gaya": "गया",
    "gayi": "गाई",
    "gaye": "गाए",
    "gao": "गाओ",
    "ga": "गा",
    "nachna": "नाचना",
    "nachta": "नाचता",
    "nacha": "नाचा",
    "nacho": "नाचो",
    "nach": "नाच",
    "girna": "गिरना",
    "pakadna": "पकड़ना",
    "pakadta": "पकड़ता",
    "pakada": "पकड़ा",
    "pakado": "पकड़ो",
    "pakad": "पकड़",
    "chhuना": "छूना",
    "chhuna": "छूना",
    "chhua": "छुआ",
    "chhoo": "छुओ",
    "chhoo": "छू",
    "maarna": "मारना",
    "maarta": "मारता",
    "maara": "मारा",
    "maaro": "मारो",
    "maar": "मार",
    "bachana": "बचाना",
    "bachata": "बचाता",
    "bachaya": "बचाया",
    "bachao": "बचाओ",
    "bacha": "बचा",
    "hilana": "हिलाना",
    "hilata": "हिलाता",
    "hilaya": "हिलाया",
    "hilao": "हिलाओ",
    "hila": "हिला",
    "jhukna": "झुकना",
    "jhukta": "झुकता",
    "jhuka": "झुका",
    "jhuko": "झुको",
    "jhuk": "झुक",
    "daalna": "डालना",
    "daalta": "डालता",
    "daala": "डाला",
    "daalo": "डालो",
    "daal": "डाल",
    "chodna": "छोड़ना",
    "peena": "पीना",
    "sulana": "सुलाना",
    "jagana": "जगाना",
    "hasana": "हँसाना",
    "rulana": "रुलाना",

    # ══════════════════════════════════════════════════════
    #  QUESTION WORDS
    # ══════════════════════════════════════════════════════
    "kya": "क्या",
    "kyun": "क्यों",
    "kyunki": "क्योंकि",
    "kaise": "कैसे",
    "kaisa": "कैसा",
    "kaisi": "कैसी",
    "kab": "कब",
    "kahan": "कहाँ",
    "kahaan": "कहाँ",
    "kaun": "कौन",
    "kitna": "कितना",
    "kitni": "कितनी",
    "kitne": "कितने",
    "konsa": "कौनसा",
    "konsi": "कौनसी",
    "konse": "कौनसे",
    "kaunsa": "कौनसा",
    "kaunsi": "कौनसी",
    "kaunse": "कौनसे",

    # ══════════════════════════════════════════════════════
    #  CONJUNCTIONS / CONNECTORS
    # ══════════════════════════════════════════════════════
    "aur": "और",
    "lekin": "लेकिन",
    "magar": "मगर",
    "par": "पर",
    "parantu": "परंतु",
    "toh": "तो",
    "to": "तो",
    "tab": "तब",
    "jab": "जब",
    "agar": "अगर",
    "yadi": "यदि",
    "warna": "वरना",
    "nahi to": "नहीं तो",
    "isliye": "इसलिए",
    "isiliye": "इसीलिए",
    "phir": "फिर",
    "phir bhi": "फिर भी",
    "tabhi": "तभी",
    "jabhi": "जभी",
    "jabse": "जबसे",
    "tabse": "तबसे",
    "jaise": "जैसे",
    "waisa": "वैसा",
    "jaisi": "जैसी",
    "waise": "वैसे",
    "jaisa": "जैसा",
    "matlab": "मतलब",
    "yani": "यानी",
    "yaani": "यानी",
    "chahe": "चाहे",
    "ya": "या",
    "aur bhi": "और भी",
    "saath hi": "साथ ही",
    "na": "ना",
    "naa": "ना",
    "bhi": "भी",
    "hi": "ही",
    "to": "तो",
    "bas": "बस",
    "sirf": "सिर्फ",
    "kewal": "केवल",
    "bilkul": "बिल्कुल",

    # ══════════════════════════════════════════════════════
    #  TIME WORDS
    # ══════════════════════════════════════════════════════
    "aaj": "आज",
    "kal": "कल",
    "parso": "परसों",
    "abhi": "अभी",
    "abhi abhi": "अभी अभी",
    "pehle": "पहले",
    "pahle": "पहले",
    "baad": "बाद",
    "baad mein": "बाद में",
    "jaldi": "जल्दी",
    "dheere": "धीरे",
    "dhire": "धीरे",
    "hamesha": "हमेशा",
    "kabhi": "कभी",
    "kabhi kabhi": "कभी कभी",
    "kabhi nahi": "कभी नहीं",
    "aksar": "अक्सर",
    "baar baar": "बार बार",
    "ek baar": "एक बार",
    "dobara": "दोबारा",
    "fir se": "फिर से",
    "subah": "सुबह",
    "shaam": "शाम",
    "raat": "रात",
    "dopahar": "दोपहर",
    "savere": "सवेरे",
    "sawere": "सवेरे",
    "ratko": "रात को",
    "din": "दिन",
    "hafte": "हफ्ते",
    "mahine": "महीने",
    "saal": "साल",
    "ghante": "घंटे",
    "minute": "मिनट",
    "second": "सेकंड",
    "der": "देर",
    "thodi der": "थोड़ी देर",
    "thode time mein": "थोड़े समय में",
    "aaj kal": "आजकल",
    "purana": "पुराना",
    "naya": "नया",
    "nayi": "नई",
    "naye": "नए",

    # ══════════════════════════════════════════════════════
    #  PLACE WORDS
    # ══════════════════════════════════════════════════════
    "yahan": "यहाँ",
    "yahaan": "यहाँ",
    "wahan": "वहाँ",
    "wahaan": "वहाँ",
    "andar": "अंदर",
    "bahar": "बाहर",
    "upar": "ऊपर",
    "neeche": "नीचे",
    "neecha": "नीचा",
    "aage": "आगे",
    "peeche": "पीछे",
    "daayein": "दाएं",
    "baayein": "बाएं",
    "daayen": "दाएं",
    "baayen": "बाएं",
    "paas": "पास",
    "door": "दूर",
    "beech": "बीच",
    "beech mein": "बीच में",
    "saath": "साथ",
    "saath mein": "साथ में",
    "ghar": "घर",
    "school": "स्कूल",
    "dukaan": "दुकान",
    "bazaar": "बाज़ार",
    "sadak": "सड़क", 
    "raasta": "रास्ता",
    "taraf": "तरफ",
    "aas paas": "आस पास",
    "idhar": "इधर",
    "udhar": "उधर",
    "kidhar": "किधर",
    "Dhundhna":"ढूंढना", # gaya

    # ══════════════════════════════════════════════════════
    #  NUMBERS (SPOKEN FORM)
    # ══════════════════════════════════════════════════════
    "ek": "एक",
    "do": "दो",
    "teen": "तीन",
    "char": "चार",
    "paanch": "पाँच",
    "chhe": "छह",
    "chhah": "छह",
    "saat": "सात",
    "aath": "आठ",
    "nau": "नौ",
    "das": "दस",
    "gyarah": "ग्यारह",
    "barah": "बारह",
    "terah": "तेरह",
    "chaudah": "चौदह",
    "pandrah": "पंद्रह",
    "solah": "सोलह",
    "satrah": "सत्रह",
    "atharah": "अठारह",
    "unnis": "उन्नीस",
    "bees": "बीस",
    "tees": "तीस",
    "chalis": "चालीस",
    "pachaas": "पचास",
    "saath": "साठ",
    "sattar": "सत्तर",
    "assi": "अस्सी",
    "nabbe": "नब्बे",
    "sau": "सौ",
    "hazaar": "हज़ार",
    "lakh": "लाख",
    "crore": "करोड़",
    "pehla": "पहला",
    "pehli": "पहली",
    "pehle": "पहले",
    "doosra": "दूसरा",
    "doosri": "दूसरी",
    "doosre": "दूसरे",
    "teesra": "तीसरा",
    "aakhri": "आखिरी",
    "aakhira": "आखिरी",

    # ══════════════════════════════════════════════════════
    #  ADJECTIVES — COMMON
    # ══════════════════════════════════════════════════════
    "accha": "अच्छा",
    "acchi": "अच्छी",
    "acche": "अच्छे",
    "bura": "बुरा",
    "buri": "बुरी",
    "bure": "बुरे",
    "bada": "बड़ा",
    "badi": "बड़ी",
    "bade": "बड़े",
    "chota": "छोटा",
    "choti": "छोटी",
    "chote": "छोटे",
    "lamba": "लंबा",
    "lambi": "लंबी",
    "lambe": "लंबे",
    "chhota": "छोटा",
    "chhoti": "छोटी",
    "chhote": "छोटे",
    "mota": "मोटा",
    "moti": "मोटी",
    "mote": "मोटे",
    "patla": "पतला",
    "patli": "पतली",
    "patle": "पतले",
    "garam": "गर्म",
    "thanda": "ठंडा",
    "thandi": "ठंडी",
    "thande": "ठंडे",
    "meetha": "मीठा",
    "meethi": "मीठी",
    "meethe": "मीठे",
    "kadwa": "कड़वा",
    "kadwi": "कड़वी",
    "kadwe": "कड़वे",
    "khatta": "खट्टा",
    "khatti": "खट्टी",
    "khatte": "खट्टे",
    "namkeen": "नमकीन",
    "teekha": "तीखा",
    "teekhi": "तीखी",
    "teekhe": "तीखे",
    "naram": "नरम",
    "sakht": "सख्त",
    "sake":"सके",
    "bhari": "भारी",
    "bhara": "भारी",#den
    "halka": "हल्का",
    "halki": "हल्की",
    "halke": "हल्के",
    "saaf": "साफ",
    "ganda": "गंदा",
    "gandi": "गंदी",
    "gande": "गंदे",
    "khubsurat": "खूबसूरत",
    "sundar": "सुंदर",
    "sundari": "सुंदरी",
    "ugly": "बदसूरत",
    "kamzor": "कमज़ोर",
    "mazboot": "मज़बूत",
    "tez": "तेज़",
    "dheema": "धीमा",
    "dhimi": "धीमी",
    "dheeme": "धीमे",
    "andhera": "अंधेरा",
    "ujala": "उजाला",
    "roshan": "रोशन",
    "geela": "गीला",
    "sukha": "सूखा",
    "purana": "पुराना",
    "naya": "नया",
    "nayi": "नई",
    "naye": "नए",
    "sasta": "सस्ता",
    "sasti": "सस्ती",
    "saste": "सस्ते",
    "mahanga": "महंगा",
    "mahangi": "महंगी",
    "mahange": "महंगे",
    "mushkil": "मुश्किल",
    "asaan": "आसान",
    "seedha": "सीधा",
    "seedhi": "सीधी",
    "seedhe": "सीधे",
    "tedha": "टेढ़ा",
    "gol": "गोल",
    "chaura": "चौड़ा",
    "chauri": "चौड़ी",
    "chaure": "चौड़े",
    "tanga": "तंगा",
    "pakka": "पक्का",
    "pakki": "पक्की",
    "pakke": "पक्के",
    "kaccha": "कच्चा",
    "khali": "खाली",
    "bhara": "भरा",
    "poora": "पूरा",
    "poorا": "पूरा",
    "adhoora": "अधूरा",
    "sahi": "सही",
    "galat": "गलत",
    "theek": "ठीक",
    "bekaar": "बेकार",
    "kaam ka": "काम का",
    "zaruri": "ज़रूरी",
    "ahem": "अहम",
    "important": "ज़रूरी",
    "khush": "खुश",
    "udaas": "उदास",
    "dukhi": "दुखी",
    "pareshan": "परेशान",
    "thaka": "थका",
    "thaki": "थकी",
    "thake": "थके",
    "beemar": "बीमार",
    "tandrust": "तंदुरुस्त",
    "taqatwar": "ताकतवर",
    "smart": "होशियार",
    "hoshiyar": "होशियार",
    "bevakoof": "बेवकूफ",
    "samajhdaar": "समझदार",
    "seedha saadha": "सीधा साधा",
    "sच्चा": "सच्चा",
    "saccha": "सच्चा",
    "sacchi": "सच्ची",
    "sacche": "सच्चे",
    "jhoota": "झूठा",
    "jhooti": "झूठी",
    "jhoote": "झूठे",
    "pyaara": "प्यारा",
    "pyaari": "प्यारी",
    "pyaare": "प्यारे",
    "bekar": "बेकार",
    "lajawaab": "लाजवाब",
    "zabardast": "ज़बरदस्त",
    "shandar": "शानदार",
    "kamaal": "कमाल",
    "behtareen": "बेहतरीन",
    "mast": "मस्त",
    "bindaas": "बिंदास",
    "chालak": "चालाक",
    "chalak": "चालाक",

    # ══════════════════════════════════════════════════════
    #  ADVERBS
    # ══════════════════════════════════════════════════════
    "bahut": "बहुत",
    "thoda": "थोड़ा",
    "thodi": "थोड़ी",
    "thode": "थोड़े",
    "zyada": "ज़्यादा",
    "jyada": "ज़्यादा",
    "kam": "कम",
    "bilkul": "बिल्कुल",
    "ekdum": "एकदम",
    "zaroor": "ज़रूर",
    "zarur": "ज़रूर",
    "shayad": "शायद",
    "lagbhag": "लगभग",
    "almost": "लगभग",
    "sirf": "सिर्फ",
    "kewal": "केवल",
    "sach mein": "सच में",
    "sach": "सच",
    "jhooth": "झूठ",
    "waise": "वैसे",
    "aise": "ऐसे",
    "aisa": "ऐसा",
    "aisi": "ऐसी",
    "itna": "इतना",
    "itni": "इतनी",
    "itne": "इतने",
    "utna": "उतना",
    "utni": "उतनी",
    "utne": "उतने",
    "kaafi": "काफी",
    "puri tarah": "पूरी तरह",
    "seedha": "सीधे",
    "dhyan se": "ध्यान से",
    "acche se": "अच्छे से",
    "tezi se": "तेज़ी से",
    "dheere dheere": "धीरे धीरे",
    "baar baar": "बार बार",
    "mil ke": "मिलकर",
    "saath mein": "साथ में",
    "akele": "अकेले",
    "dono": "दोनों",
    "sab": "सब",
    "sabhi": "सभी",
    "kuch": "कुछ",
    "koi": "कोई",
    "har": "हर",
    "har ek": "हर एक",
    "hare ek": "हर एक",

    # ══════════════════════════════════════════════════════
    #  NEGATION
    # ══════════════════════════════════════════════════════
    "nahi": "नहीं",
    "nahin": "नहीं",
    "na": "ना",
    "naa": "ना",
    "mat": "मत",
    "bilkul nahi": "बिल्कुल नहीं",
    "kabhi nahi": "कभी नहीं",
    "kuch nahi": "कुछ नहीं",
    "koi nahi": "कोई नहीं",

    # ══════════════════════════════════════════════════════
    #  COMMON NOUNS — BODY
    # ══════════════════════════════════════════════════════
    "haath": "हाथ",
    "pair": "पैर",
    "aankhein": "आँखें",
    "aankh": "आँख",
    "kaan": "कान",
    "naak": "नाक",
    "mooh": "मुँह",
    "muh": "मुँह",
    "daant": "दाँत",
    "zubaan": "ज़ुबान",
    "bal": "बाल",
    "chehra": "चेहरा",
    "gaal": "गाल",
    "maatha": "माथा",
    "gardan": "गर्दन",
    "kaandha": "कंधा",
    "seena": "सीना",
    "pet": "पेट",
    "kamar": "कमर",
    "dil": "दिल",
    "dimaag": "दिमाग",
    "khoon": "खून",
    "haddi": "हड्डी",
    "chamdi": "चमड़ी",
    "ungali": "उंगली",
    "angutha": "अंगूठा",
    "godh": "गोद",
    "peeth": "पीठ",
    "naaf": "नाभि",

    # ══════════════════════════════════════════════════════
    #  COMMON NOUNS — FAMILY
    # ══════════════════════════════════════════════════════
    "maa": "माँ",
    "ma": "माँ",
    "ammi": "अम्मी",
    "baap": "बाप",
    "papa": "पापा",
    "abbu": "अब्बू",
    "bhai": "भाई",
    "behen": "बहन",
    "beta": "बेटा",
    "beti": "बेटी",
    "dada": "दादा",
    "dadi": "दादी",
    "nana": "नाना",
    "nani": "नानी",
    "chacha": "चाचा",
    "chachi": "चाची",
    "mama": "मामा",
    "mami": "मामी",
    "fufa": "फूफा",
    "bua": "बुआ",
    "mausa": "मौसा",
    "mausi": "मौसी",
    "dost": "दोस्त",
    "yaar": "यार",
    "saathi": "साथी",
    "pati": "पति",
    "patni": "पत्नी",
    "biwi": "बीवी",
    "shauhar": "शौहर",
    "baccha": "बच्चा",
    "bachche": "बच्चे",
    "bacha": "बच्चा",
    "ladka": "लड़का",
    "ladki": "लड़की",
    "aadmi": "आदमी",
    "aurat": "औरत",
    "insaan": "इंसान",
    "banda": "बंदा",

    # ══════════════════════════════════════════════════════
    #  COMMON NOUNS — EVERYDAY OBJECTS
    # ══════════════════════════════════════════════════════
    "paani": "पानी",
    "khana": "खाना",
    "roti": "रोटी",
    "chawal": "चावल",
    "daal": "दाल",
    "sabzi": "सब्ज़ी",
    "doodh": "दूध",
    "chai": "चाय",
    "kapda": "कपड़ा",
    "kapde": "कपड़े",
    "joota": "जूता",
    "joote": "जूते",
    "kitaab": "किताब",
    "copy": "कॉपी",
    "kalam": "कलम",
    "ghadi": "घड़ी",
    "phone": "फ़ोन",
    "paisa": "पैसा",
    "paise": "पैसे",
    "daam": "दाम",
    "cheez": "चीज़",
    "kaam": "काम",
    "baat": "बात",
    "sawaal": "सवाल",
    "jawaab": "जवाब",
    "naam": "नाम",
    "jagah": "जगह",
    "taraf": "तरफ",
    "waqt": "वक्त",
    "samay": "समय",
    "zaroorat": "ज़रूरत",
    "zarurat": "ज़रूरत",
    "madad": "मदद",
    "taklif": "तकलीफ",
    "dard": "दर्द",
    "khushi": "खुशी",
    "dukh": "दुख",
    "pyaar": "प्यार",
    "nafrat": "नफ़रत",
    "izzat": "इज़्ज़त",
    "himmat": "हिम्मत",
    "hosla": "हौसला",
    "umeed": "उम्मीद",
    "vishwas": "विश्वास",
    "bharosa": "भरोसा",
    "fikar": "फ़िक्र",
    "chinta": "चिंता",
    "khatra": "खतरा",
    "faida": "फायदा",
    "nuksan": "नुकसान",
    "galti": "गलती",
    "seekh": "सीख",
    "tajarba": "तजुर्बा",
    "anubhav": "अनुभव",
    "use":"यूज़",
    "usse":"उसे",

    # ══════════════════════════════════════════════════════
    #  EXPRESSIONS / FILLERS
    # ══════════════════════════════════════════════════════
    "haan":"हाँ",
    "han": "हाँ",
    "ha": "हाँ",
    "nahin": "नहीं",
    "nahi": "नहीं",
    "theek hai": "ठीक है",
    "theek": "ठीक",
    "okay": "ठीक है",
    "chalo": "चलो",
    "aacha": "अच्छा",
    "wah": "वाह",
    "waah": "वाह",
    "arre": "अरे",
    "arrey": "अरे",
    "oho": "ओहो",
    "oye": "ओए",
    "yaar": "यार",
    "bhai": "भाई",
    "dekho": "देखो",
    "suno": "सुनो",
    "samjhe": "समझे",
    "samjha": "समझा",
    "pata hai": "पता है",
    "pata nahi": "पता नहीं",
    "maloom": "मालूम",
    "maloom nahi": "मालूम नहीं",
    "koi baat nahi": "कोई बात नहीं",
    "shukriya": "शुक्रिया",
    "dhanyavaad": "धन्यवाद",
    "maafi": "माफी",
    "sorry": "माफ करो",
    "please": "कृपया",
    "bas": "बस",
    "bas karo": "बस करो",
    "rukke": "रुको",
    "chup": "चुप",
    "chup raho": "चुप रहो",
    "bolo": "बोलो",
    "batao": "बताओ",
    "sunao": "सुनाओ",
    "dikhao": "दिखाओ",
    "lao": "लाओ",
    "jao": "जाओ",
    "aao": "आओ",
    "ruko": "रुको",
    "uthो": "उठो",
    "socho": "सोचो",
    "dekho": "देखो",
    "mano": "मानो",
    "lo": "लो",
    "do": "दो",
    "karo": "करो",
    "rehne do": "रहने दो",
    "chhod do": "छोड़ दो",
    "mat karo": "मत करो",

    # ══════════════════════════════════════════════════════
    #  EDUCATION / SCHOOL / STUDY RELATED
    # ══════════════════════════════════════════════════════
    "padhai": "पढ़ाई",
    "seekhna": "सीखना",
    "seekho": "सीखो",
    "pariksha": "परीक्षा",
    "imtihaan": "इम्तिहान",
    "marks": "नंबर",
    "number": "नंबर",
    "result": "परिणाम",
    "class": "कक्षा",
    "kaksha": "कक्षा",
    "teacher": "शिक्षक",
    "adhyapak": "अध्यापक",
    "vidyarthi": "विद्यार्थी",
    "chhatra": "छात्र",
    "sawaal": "सवाल",
    "prashn": "प्रश्न",
    "uttar": "उत्तर",
    "jawaab": "जवाब",
    "gyaan": "ज्ञान",
    "jankari": "जानकारी",
    "definition": "परिभाषा",
    "paribhasha": "परिभाषा",
    "udaharan": "उदाहरण",
    "example": "उदाहरण",
    "niyam": "नियम",
    "sutra": "सूत्र",
    "siddhant": "सिद्धांत",
    
    "adhyay": "अध्याय",
    "topic": "विषय",
    "vishay": "विषय",
    "project": "परियोजना",
    "homework": "गृहकार्य",
    "notes": "नोट्स",

    # ══════════════════════════════════════════════════════
    #  MATH RELATED (SPOKEN)
    # ══════════════════════════════════════════════════════
    "jodo": "जोड़ो",
    "jodna": "जोड़ना",
    "jod": "जोड़",
    "ghatao": "घटाओ",
    "ghatana": "घटाना",
    "ghata": "घटा",
    "guno": "गुणा करो",
    "guna": "गुणा",
    "gunna": "गुणा",
    "bhag": "भाग",
    "bhago": "भाग करो",
    "bhagna": "भागना",
    "barabar": "बराबर",
    "barabar hai": "बराबर है",
    "gyarah": "ग्यारह",
    "nikalna": "निकालना",
    "nikalo": "निकालो",
    "hisaab": "हिसाब",
    "ganit": "गणित",
    "sankhya": "संख्या",
    "ank": "अंक",
    "answer": "उत्तर",
    "हल": "हल",
    "hal": "हल",
    "solve": "हल करो",

    # ══════════════════════════════════════════════════════
    #  SCIENCE RELATED (SPOKEN)
    # ══════════════════════════════════════════════════════
    "prakriya": "प्रक्रिया",
    "shakti": "शक्ति",
    "urja": "ऊर्जा",
    "pani": "पानी",
    "hawa": "हवा",
    "aag": "आग",
    "mitti": "मिट्टी",
    "ped": "पेड़",
    "paudha": "पौधा",
    "jantu": "जंतु",
    "jaanwar": "जानवर",
    "pakshi": "पक्षी",
    "cheeti": "चींटी",
    "insect": "कीड़ा",
    "keeda": "कीड़ा",
    "andaa": "अंडा",
    "beej": "बीज",
    "jad": "जड़",
    "patti": "पत्ती",
    "phool": "फूल",
    "phal": "फल",

    # ══════════════════════════════════════════════════════
    #  EMOTIONS & FEELINGS
    # ══════════════════════════════════════════════════════
    "khushi": "खुशी",
    "dukh": "दुख",
    "gussa": "गुस्सा",
    "nafrat": "नफ़रत",
    "pyaar": "प्यार",
    "mohabbat": "मोहब्बत",
    "dard": "दर्द",
    "takleef": "तकलीफ़",
    "pareshan": "परेशान",
    "tension": "टेंशन",
    "darr": "डर",
    "dar": "डर",
    "himmat": "हिम्मत",
    "hosla": "हौसला",
    "sharm": "शर्म",
    "garv": "गर्व",
    "naaz": "नाज़",
    "aaramdayak": "आरामदायक",
    "chain": "चैन",
    "sukoon": "सुकून",
    "bechain": "बेचैन",
    "ghabrana": "घबराना",
    "ghabrahat": "घबराहट",
    "hairaan": "हैरान",
    "pareshaan": "परेशान",
    "achamba": "अचंभा",
    "ajeeb": "अजीब",
    "taajjub": "ताज्जुब",
    "majaa": "मज़ा",
    "maja": "मज़ा",
    "bore": "बोर",
    "thakan": "थकान",
    "neend": "नींद",
    "bhook": "भूख",
    "pyaas": "प्यास",

    # ══════════════════════════════════════════════════════
    #  ACTIONS — DAILY LIFE
    # ══════════════════════════════════════════════════════
    "nahana": "नहाना",
    "nahata": "नहाता",
    "nahati": "नहाती",
    "nahao": "नहाओ",
    "naha": "नहा",
    "kapde pahnna": "कपड़े पहनना",
    "pahanna": "पहनना",
    "pahanta": "पहनता",
    "pahno": "पहनो",
    "pahan": "पहन",
    "utaarna": "उतारना",
    "utaaro": "उतारो",
    "utaar": "उतार",
    "saaf karna": "साफ करना",
    "saaf karo": "साफ करो",
    "dhona": "धोना",
    "dhota": "धोता",
    "dhoti": "धोती",
    "dhoe": "धोए",
    "dhoo": "धोओ",
    "dho": "धो",
    "poochna": "पोंछना",
    "poochna": "पूछना",
    "sulana": "सुलाना",
    "jagana": "जगाना",
    "khilana": "खिलाना",
    "pilana": "पिलाना",
    "nindna": "नींद आना",
    "khaana banana": "खाना बनाना",
    "baazaar jaana": "बाज़ार जाना",
    "school jaana": "स्कूल जाना",
    "ghar aana": "घर आना",
    "kaam karna": "काम करना",
    "khel khelna": "खेल खेलना",
    "ghumna firna": "घूमना फिरना",

    # ══════════════════════════════════════════════════════
    #  COMMON PHRASES / IDIOMS
    # ══════════════════════════════════════════════════════
    "dhyan rakhna": "ध्यान रखना",
    "dhyan rakho": "ध्यान रखो",
    "dhyan de": "ध्यान दे",
    "khayal rakhna": "ख़याल रखना",
    "samajh aaya": "समझ आया",
    "samajh nahi aaya": "समझ नहीं आया",
    "yaad rakhna": "याद रखना",
    "yaad rakho": "याद रखो",
    "yaad raho": "याद रहो",
    "kaam aana": "काम आना",
    "kaam aata hai": "काम आता है",
    "maan lo": "मान लो", # formula
    "soch lo": "सोच लो",
    "dekh lo": "देख लो",
    "kar lo": "कर लो",
    "le lo": "ले लो",
    "de do": "दे दो",
    "bata do": "बता दो",
    "bol do": "बोल दो",
    "pooch lo": "पूछ लो",
    "likh lo": "लिख लो",
    "padh lo": "पढ़ लो",
    "samajh lo": "समझ लो",
    "sun lo": "सुन लो",
    "jaan lo": "जान लो",
    "khyal rakh": "ख़याल रख",
    "mushkil nahi": "मुश्किल नहीं",
    "asaan hai": "आसान है",
    "ho jayega": "हो जाएगा",
    "ho gaya": "हो गया",
    "ho gayi": "हो गई",
    "ho gaye": "हो गए",
    "kar liya": "कर लिया",
    "kar diya": "कर दिया",
    "de diya": "दे दिया",
    "le liya": "ले लिया",
    "bata diya": "बता दिया",
    "dekh liya": "देख लिया",
    "sun liya": "सुन लिया",
    "samajh liya": "समझ लिया",
    "padh liya": "पढ़ लिया",
    "likh liya": "लिख लिया",
    "mil gaya": "मिल गया",
    "mil gayi": "मिल गई",
    "aa gaya": "आ गया",
    "aa gayi": "आ गई",
    "chala gaya": "चला गया",
    "chali gayi": "चली गई",
    "ruk gaya": "रुक गया",
    "khatam": "खत्म",
    "khatam ho gaya": "खत्म हो गया",
    "shuru": "शुरू",
    "shuroo": "शुरू",
    "shuru karo": "शुरू करो",
    "shuru ho gaya": "शुरू हो गया",

    # ══════════════════════════════════════════════════════
    #  TEACHING / EXPLAINING SPECIFIC WORDS
    # ══════════════════════════════════════════════════════
    "matlab hai": "मतलब है",
    "matlab hua": "मतलब हुआ",
    "matlab yeh hai": "मतलब यह है",
    "yani ki": "यानी कि",
    "simple shabdon mein": "सरल शब्दों में",
    "seedhe seedhe": "सीधे सीधे",
    "ek baar phir": "एक बार फिर",
    "dobara sunna": "दोबारा सुनना",
    "isko samjho": "इसको समझो",
    "dhyan se suno": "ध्यान से सुनो",
    "dhyan se dekho": "ध्यान से देखो",
    "yaad karo": "याद करो",
    "yaad karna": "याद करना",
    "bhool mat": "भूलो मत",
    "yaad rahe": "याद रहे",
    "important hai": "ज़रूरी है",
    "zaruri hai": "ज़रूरी है",
    "use karo": "उपयोग करो",
    "istemal karo": "इस्तेमाल करो",
    "lagao": "लगाओ",
    "apply karo": "लगाओ",
    "sahi hai": "सही है",
    "galat hai": "गलत है",
    "dekha": "देखा",
    "socha": "सोचा",
    "pata chala": "पता चला",
    "samajh aaya": "समझ आया",
    "clear hai": "समझ आया",
    "clear hua": "समझ आया",
    "pakka": "पक्का",
    "bilkul sahi": "बिल्कुल सही",
    "bahut accha": "बहुत अच्छा",
    "shuruaat": "शुरुआत",
    "ant": "अंत",
    "dono": "दोनों",
    "teeno": "तीनों",
    "sabhi": "सभी",
    "koi bhi": "कोई भी",
    "kuch bhi": "कुछ भी",
    "har koi": "हर कोई",
    "har jagah": "हर जगह",
    "har baar": "हर बार",
    "pehli baar": "पहली बार",
    "aakhri baar": "आखिरी बार",

    # ══════════════════════════════════════════════════════
    #  POSTPOSITIONS (CASE MARKERS)
    # ══════════════════════════════════════════════════════
    "ka": "का",
    "ki": "की",
    "ke": "के",
    "ko": "को",
    "se": "से",
    "ne": "ने",
    "mein": "में",
    "pe": "पे",
    "par": "पर",
    "tak": "तक",
    "ke liye": "के लिए",
    "ke saath": "के साथ",
    "ke baad": "के बाद",
    "ke pehle": "के पहले",
    "ke upar": "के ऊपर",
    "ke neeche": "के नीचे",
    "ke andar": "के अंदर",
    "ke bahar": "के बाहर",
    "ke paas": "के पास",
    "ke door": "के दूर",
    "ke beech": "के बीच",
    "ke bina": "के बिना",
    "ki wajah se": "की वजह से",
    "ki taraf": "की तरफ",
    "ki jagah": "की जगह",
    "ke kaaran": "के कारण",
    "ke baare mein": "के बारे में",
    "ke liye": "के लिए",

    # ══════════════════════════════════════════════════════
    #  MISC VERY COMMON WORDS
    # ══════════════════════════════════════════════════════
    "kuch": "कुछ",
    "sab kuch": "सब कुछ",
    "koi": "कोई",
    "koई": "कोई",
    "har": "हर",
    "wala": "वाला",
    "wali": "वाली",
    "wale": "वाले",
    "waala": "वाला",
    "waali": "वाली",
    "waale": "वाले",
    "jaise wala": "जैसा वाला",
    "tarah": "तरह",
    "taraf": "तरफ",
    "jagah": "जगह",
    "wajah": "वजह",
    "kaaran": "कारण",
    "cheez": "चीज़",
    "cheezein": "चीज़ें",
    "baat": "बात",
    "baatein": "बातें",
    "kaam": "काम",
    "kaam karo": "काम करो",
    "zaroorat": "ज़रूरत",
    "zarurat": "ज़रूरत",
    "madad": "मदद",
    "sawal": "सवाल",
    "jawab": "जवाब",
    "faisla": "फैसला",
    "chunaav": "चुनाव",
    "raasta": "रास्ता",
    "tarika": "तरीका",
    "mukaam": "मुकाम",
    "manzil": "मंज़िल",
    "sapna": "सपना",
    "sach": "सच",
    "jhooth": "झूठ",
    "sachai": "सच्चाई",
    "lafz": "लफ़्ज़",
    "shabd": "शब्द",
    "vaakya": "वाक्य",
    "kahani": "कहानी",
    "itihas": "इतिहास",
    "bhavishya": "भविष्य",
    "vartman": "वर्तमान",
    "duniya": "दुनिया",
    "zameen": "ज़मीन",
    "aasman": "आसमान",
    "suraj": "सूरज",
    "chand": "चाँद",
    "sitaare": "सितारे",
    "taare": "तारे",
    "baarish": "बारिश",
    "dhoop": "धूप",
    "andhi": "आँधी",
    "toofaan": "तूफ़ान",
    "bijli": "बिजली",
    "pahaad": "पहाड़",
    "naddi": "नदी",
    "nadi": "नदी",
    "samudra": "समुद्र",
    "jungle": "जंगल",
    "gaon": "गाँव",
    "shehar": "शहर",
    "desh": "देश",
    "sarkaar": "सरकार",
    "kanoon": "क़ानून",
    "police": "पुलिस",
    "doctor": "डॉक्टर",
    "dawai": "दवाई",
    "ilaj": "इलाज",
    "hospital": "अस्पताल",
    "daftar": "दफ़्तर",
    "bazaar": "बाज़ार",
    "dukaan": "दुकान",
    "bank": "बैंक",
    "pul": "पुल",
    "raaste": "रास्ते",
    "gaadi": "गाड़ी",
    "bus": "बस",
    "train": "ट्रेन",
    "hawai jahaz": "हवाई जहाज़",
    "naav": "नाव",
}
#  1